### ISSUE TITLE
Opening Inventory for Player

### ISSUE THREAD

**Issue by 20zinnm** [SpongePowered/SpongeAPI#1085]
When I try to open a custom inventory for a player, I get
```java
[18:07:21] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'buy' for source EntityPlayerMP['AniSkywalker'/39, l='world', x=154.50, y=66.00, z=-6.50]: Method net/minecraft/entity/player/EntityPlayerMP.openInventory(Lorg/spongepowered/api/item/inventory/Inventory;)V is abstract
java.lang.AbstractMethodError: Method net/minecraft/entity/player/EntityPlayerMP.openInventory(Lorg/spongepowered/api/item/inventory/Inventory;)V is abstract
	at net.minecraft.entity.player.EntityPlayerMP.openInventory(EntityPlayerMP.java) ~[lf.class:?]
	at net.buycraft.plugin.sponge.gui.GuiView.open(GuiView.java:178) ~[GuiView.class:?]
	at net.buycraft.plugin.sponge.command.GuiCmd.execute(GuiCmd.java:42) ~[GuiCmd.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:169) ~[ChildCommandElementExecutor.class:1.8.9-1732-3.1.0-BETA-1159]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:332) ~[CommandSpec.class:1.8.9-1732-3.1.0-BETA-1159]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1732-3.1.0-BETA-1159]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:252) [SpongeCommandManager.class:1.8.9-1732-3.1.0-BETA-1159]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:106) [PacketUtil.class:1.8.9-1732-3.1.0-BETA-1159]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:51) [fh$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
> 
```
Here's the code:
```java
viewer.openInventory(inventory);
```
```java
inventory = CustomInventory.builder().name(getFixedTranslation()).size(getSize() + 9).build();
```

No IDE/Build errors. Reliably fails in both SpongeForge and SpongeVanilla (both latest).

**Comment by 20zinnm** [comment]
I was informed this hasn't been implemented yet. Seems like a rather major feature to not be implemented.

**Comment by windy1** [comment]
Contributions are always welcomed @20zinnm! :)

**Comment by 20zinnm** [comment]
@windy1 Where would this need to be implemented? It's a mission-critical portion of this plugin so I'm happy to speed up the process. It seems Chest inventories are already implemented so it shouldn't be TOO hard (he says that now).

**Comment by windy1** [comment]
@20zinnm Without looking at it myself I would look at uses of Packet 0x2D (open window) and just work your way up. Check out MixinInventoryPlayer as well.

**Comment by 20zinnm** [comment]
@windy1 I'll see what I can (or can't) do :smile:
