### ISSUE TITLE
EntityPlayerMP cannot be cast to java.lang.Iterable in GenericArguments.player

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeAPI#1131]
Using `spongeforge-1.8.9-1763-4.1.0-BETA-1190`. Any command handler in our custom plugins that accepts a `GenericArguments.player` triggers the following error:

```
java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to java.lang.Iterable
    at org.spongepowered.api.command.args.GenericArguments$PlayerCommandElement.parseValue(GenericArguments.java:992) ~[GenericArguments$PlayerCommandElement.class:1.8.9-1763-4.1.0-BETA-1190]
    at org.spongepowered.api.command.args.CommandElement.parse(CommandElement.java:83) ~[CommandElement.class:1.8.9-1763-4.1.0-BETA-1190]
    at org.spongepowered.api.command.args.GenericArguments$SequenceCommandElement.parse(GenericArguments.java:235) ~[GenericArguments$SequenceCommandElement.class:1.8.9-1763-4.1.0-BETA-1190]
    at org.spongepowered.api.command.spec.CommandSpec.populateContext(CommandSpec.java:284) ~[CommandSpec.class:1.8.9-1763-4.1.0-BETA-1190]
    at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:330) ~[CommandSpec.class:1.8.9-1763-4.1.0-BETA-1190]
    at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1763-4.1.0-BETA-1190]
    at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:268) [SpongeCommandManager.class:1.8.9-1763-4.1.0-BETA-1190]
    at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
    at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:106) [PacketUtil.class:1.8.9-1763-4.1.0-BETA-1190]
    at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:51) [fh$1.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
    at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
```

**Comment by Zidane** [comment]
Fixed in latest API.
