### ISSUE TITLE
SpawnEntityEvent MUST have a SpawnCause as the root

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeAPI#1132]
idk howto reproduce, only customnpc mod on the spongeforge installed

```ruby
[12:42:43] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: SpawnEntityEvent MUST have a SpawnCause as the root!
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_74]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_74]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.IllegalArgumentException: SpawnEntityEvent MUST have a SpawnCause as the root!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.8.9.jar:?]
        at org.spongepowered.api.event.impl.AbstractSpawnEntityEvent.init(AbstractSpawnEntityEvent.java:39) ~[AbstractSpawnEntityEvent.class:1.8.9-1763-4.1.0-BETA-1190]
        at org.spongepowered.api.event.impl.CreativeInventoryEvent$Drop$Impl.<init>(Unknown Source) ~[?:?]
        at org.spongepowered.api.event.impl.CreativeInventoryEvent$Drop$Factory.apply(Unknown Source) ~[?:?]
        at org.spongepowered.api.event.impl.CreativeInventoryEvent$Drop$Factory.apply(Unknown Source) ~[?:?]
        at org.spongepowered.api.event.SpongeEventFactoryUtils.createEventImpl(SpongeEventFactoryUtils.java:82) ~[SpongeEventFactoryUtils.class:1.8.9-1763-4.1.0-BETA-1190]
        at org.spongepowered.api.event.SpongeEventFactory.createCreativeInventoryEventDrop(SpongeEventFactory.java:3479) ~[SpongeEventFactory.class:1.8.9-1763-4.1.0-BETA-1190]
        at org.spongepowered.common.event.SpongeCommonEventFactory.handleCreativeClickInventoryEvent(SpongeCommonEventFactory.java:254) ~[SpongeCommonEventFactory.class:1.8.9-1763-4.1.0-BETA-1190]
        at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:501) ~[CauseTracker.class:1.8.9-1763-4.1.0-BETA-1190]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:108) ~[PacketUtil.class:1.8.9-1763-4.1.0-BETA-1190]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:51) ~[fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_74]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
```

**Comment by gabizou** [comment]
This is an implementation issue, not an API issue, Related is SpongePowered/SpongeCommon#571
