### ISSUE TITLE
Negative enchantment value causes crashes

### ISSUE THREAD

**Issue by mbax** [SpongePowered/SpongeAPI#1337]
The constructor for `ItemEnchantment` throws an exception if the enchantment level is less than 0. This is a totally rational thing to want to do, except this results in all sorts of messes if a player has an item with a negative value. 

Simple example running a 1.10 server, with just a plugin to create the initial scenario (because it's possible to do this in SpongeAPI. See #1338).

```
Description: Ticking player

java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
    at org.spongepowered.api.data.meta.ItemEnchantment.<init>(ItemEnchantment.java:57)
    at org.spongepowered.common.data.util.NbtDataUtil.getItemEnchantments(NbtDataUtil.java:352)
    at org.spongepowered.common.data.processor.data.item.ItemEnchantmentDataProcessor.getVal(ItemEnchantmentDataProcessor.java:70)
    at org.spongepowered.common.data.processor.data.item.ItemEnchantmentDataProcessor.getVal(ItemEnchantmentDataProcessor.java:49)
    at org.spongepowered.common.data.processor.common.AbstractSingleDataSingleTargetProcessor.from(AbstractSingleDataSingleTargetProcessor.java:129)
    at org.spongepowered.common.data.util.DataProcessorDelegate.from(DataProcessorDelegate.java:98)
    at net.minecraft.item.ItemStack.get(ItemStack.java:71)
    at net.minecraft.item.Item.getData(Item.java:111)
    at net.minecraft.item.Item.getManipulatorsFor(Item.java:104)
    at net.minecraft.item.ItemStack.getContainers(ItemStack.java:258)
    at org.spongepowered.common.item.inventory.SpongeItemStackSnapshot.<init>(SpongeItemStackSnapshot.java:87)
    at net.minecraft.item.ItemStack.createSnapshot(ItemStack.java:233)
    at net.minecraft.inventory.Container.func_75142_b(Container.java:107)
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:254)
    at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:97)
    at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$0(WorldServer.java:1141)
    at net.minecraft.world.World.func_72866_a(World.java:1962)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
    at net.minecraft.world.World.func_72870_g(World.java:1932)
    at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:647)
    at net.minecraft.world.World.func_72939_s(World.java:1240)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by Rasgnarok** [comment]
You don't even need to set the enchantment level to a negative value to reproduce, see
https://github.com/SpongePowered/SpongeForge/issues/865

**Comment by mbax** [comment]
@Rasgnarok see #1138, referenced above, for how to do it with a positive value.

**Comment by parlough** [comment]
Due to the overflow issue being gone is this still an issue?

**Comment by parlough** [comment]
We do not place these limits any longer, besides being with `Short.MIN_VALUE` and `Short.MAX_VALUE`, leaving it up to the plugin if there are issues with negative or large values. It is still recommended to stay within `EnchantmentType#getMinimumLevel` and `EnchantmentType#getMaximumLevel` though.

See https://github.com/SpongePowered/SpongeAPI/pull/1687 for more information.
