### ISSUE TITLE
Data serialization inconsistencies in MemoryDataView

### ISSUE THREAD

**Issue by simon816** [SpongePowered/SpongeAPI#1388]
There are a few inconsistencies when seralizing an object with a registered `DataSerializer`/`DataTranslator`

Test 1 serializes as expected
```java
data.set(DataQuery.of("Test1"), new Vector3i(1, 2, 3));
```
With SpongeForge 1762 (4.2.0)
```
MemoryDataContainer {
    map = {
        Test1 = MemoryDataView {
            path = Test1, map = {
                x = 1,
                y = 2,
                z = 3
            }
        }
    }
}
```
With SpongeForge 1798 (5.0.0)
```
MemoryDataContainer {
    safety = ALL_DATA_CLONED, map = {
        Test1 = MemoryDataView {
            path = Test1, safety = ALL_DATA_CLONED, map = {
                x = 1,
                y = 2,
                z = 3
            }
        }
    }
}
```

Test 2 serializes as expected
```java
Map<Object, Object> map = Maps.newHashMap();
map.put("Test2_Map", new Vector3i(2, 3, 4));
data.set(DataQuery.of("Test2"), map);
```
With SpongeForge 1762 (4.2.0)
```
MemoryDataContainer {
    map = {
        Test2 = MemoryDataView {
            path = Test2, map = {
                Test2_Map = MemoryDataView {
                    path = Test2.Test2_Map, map = {
                        x = 2,
                        y = 3,
                        z = 4
                    }
                }
            }
        }
    }
}
```
With SpongeForge 1798 (5.0.0)
```
MemoryDataContainer {
    safety = ALL_DATA_CLONED, map = {
        Test2 = MemoryDataView {
            path = Test2, safety = ALL_DATA_CLONED, map = {
                Test2_Map = MemoryDataView {
                    path = Test2.Test2_Map, safety = ALL_DATA_CLONED, map = {
                        x = 2,
                        y = 3,
                        z = 4
                    }
                }
            }
        }
    }
}
```

Test 3 - Fails on 1.8.9
```java
Map<Object, Object> map = Maps.newHashMap();
map.put("Test3_Map", Lists.newArrayList(new Vector3i(3, 4, 5)));
data.set(DataQuery.of("Test3"), map);
```
With SpongeForge 1762 (4.2.0)
```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.flowpowered.math.vector.Vector3i
        at org.spongepowered.common.data.persistence.DataSerializers$8.serialize(DataSerializers.java:271) ~[DataSerializers$8.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.api.data.MemoryDataView.setCollection(MemoryDataView.java:347) ~[MemoryDataView.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.api.data.MemoryDataView.set(MemoryDataView.java:283) ~[MemoryDataView.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.api.data.MemoryDataView.setMap(MemoryDataView.java:398) ~[MemoryDataView.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.api.data.MemoryDataView.set(MemoryDataView.java:285) ~[MemoryDataView.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.api.data.MemoryDataContainer.set(MemoryDataContainer.java:53) ~[MemoryDataContainer.class:1.8.9-1890-4.2.0-BETA-1762]
        at com.simon816.test.ErrorTest.test(ErrorTest.java:53) ~[ErrorTest.class:?]
```
With SpongeForge 1798 (5.0.0)
```
MemoryDataContainer {
    safety = ALL_DATA_CLONED, map = {
        Test3 = MemoryDataView {
            path = Test3, safety = ALL_DATA_CLONED, map = {
                Test3_Map = [MemoryDataContainer {
                    safety = ALL_DATA_CLONED, map = {
                        x = 3,
                        y = 4,
                        z = 5
                    }
                }]
            }
        }
    }
}
```

Test 4 does NOT serialize the vector. Causes errors when translating to other forms (e.g NBT)
```java
Map<Object, Object> map = Maps.newHashMap();
map.put("Test4_Map", Lists.newArrayList(new Vector3i(4, 5, 6)));
data.set(DataQuery.of("Test4"), Lists.<Map<?, ?>>newArrayList(map));
```
With SpongeForge 1762 (4.2.0)
```
MemoryDataContainer {
    map = {
        Test4 = [{
            Test4_Map = [(4, 5, 6)]
        }]
    }
}
```
With SpongeForge 1798 (5.0.0)
```
MemoryDataContainer {
    safety = ALL_DATA_CLONED, map = {
        Test4 = [{
            Test4_Map = [(4, 5, 6)]
        }]
    }
}
```

Test 5 - Fails on 1.8.9
```java
data.set(DataQuery.of("Test5"), Lists.newArrayList(new Vector3i(5, 6, 7)));
```
With SpongeForge 1762 (4.2.0)
```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.flowpowered.math.vector.Vector3i
        at org.spongepowered.common.data.persistence.DataSerializers$8.serialize(DataSerializers.java:271) ~[DataSerializers$8.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.api.data.MemoryDataView.setCollection(MemoryDataView.java:347) ~[MemoryDataView.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.api.data.MemoryDataView.set(MemoryDataView.java:283) ~[MemoryDataView.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.api.data.MemoryDataContainer.set(MemoryDataContainer.java:53) ~[MemoryDataContainer.class:1.8.9-1890-4.2.0-BETA-1762]
        at com.simon816.test.ErrorTest.test(ErrorTest.java:59) ~[ErrorTest.class:?]
        at com.simon816.test.ErrorTest.lambda$0(ErrorTest.java:36) ~[ErrorTest.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:331) ~[CommandSpec.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1762]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279) [SpongeCommandManager.class:1.8.9-1890-4.2.0-BETA-1762]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:380) [ko.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:345) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
```
With SpongeForge 1798 (5.0.0)
```
MemoryDataContainer {
    safety = ALL_DATA_CLONED, map = {
        Test5 = [MemoryDataContainer {
            safety = ALL_DATA_CLONED, map = {
                x = 5,
                y = 6,
                z = 7
            }
        }]
    }
}
```

**Comment by gabizou** [comment]
Aside from the class cast exception that @Deamon5550 fixed in https://github.com/SpongePowered/SpongeAPI/commit/52ae682fa2605b47b017aebba6411ec421cfc7ea, there's no real difference between the two mappings.

**Comment by simon816** [comment]
Test 4 is broken on both versions.

Also, if I try to set a data on a `DataView` with an empty `DataQuery`, it throws an IOOBE. What's the use of an empty query?
```
java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:313) ~[guava-17.0.jar:?]
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:295) ~[guava-17.0.jar:?]
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65) ~[guava-17.0.jar:?]
	at org.spongepowered.api.data.MemoryDataView.set(MemoryDataView.java:283) ~[MemoryDataView.class:?]
	at org.spongepowered.api.data.MemoryDataContainer.set(MemoryDataContainer.java:53) ~[MemoryDataContainer.class:?]
	at org.spongepowered.api.data.MemoryDataContainer.set(MemoryDataContainer.java:1) ~[MemoryDataContainer.class:?]
```

**Comment by gabizou** [comment]
@simon816 you can't set anything on an empty `DataQuery` since that is the "self" object.

**Comment by gabizou** [comment]
@simon816 I don't see how this isn't working....

**Comment by simon816** [comment]
So test 4 is a list with a map with an entry value of a list with a vector
(i.e. `List [ Map { String->List[ Vector ] } ]`)
I've traced through the steps:
`set(DataQuery, Ojbject)` Entry point
[`setCollection(String, Collection)`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/MemoryDataView.java#L275) Unwraps the list
[`ensureSerialization(Map)`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/MemoryDataView.java#L337) Unwraps the map
[`ensureSerialization(Collection)`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/MemoryDataView.java#L385) Unwraps the inner list
Then the object is just appended to the `ImmutableList` if it's not a `Collection` or `DataSerializable`
[`objectBuilder.add(element)`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/MemoryDataView.java#L369)

The problem appears to be that `ensureSerialization` doesn't go through the same rigorous instanceof matching that `set(DataQuery, Object)` does. thus leading to arbitrary objects being appended when it's inside a collection.

The fix would be to have one central method that converts an object to either a datacontainer or a base type.

**Comment by ImMorpheus** [comment]
MemoryDataView was moved to the implementation.

It still needs to be tested to confirm it's still relevant but in the meantime I'm moving this to SC
