### ISSUE TITLE
GenericArguments.enumValue assumes capitalized names.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1396]
Using an enum that goes against Java naming conventions creates the following exception.

```
ava.lang.IllegalArgumentException: No enum constant au.id.rleach.pokeparticles.EffectType.FIESTA
    at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_91]
    at org.spongepowered.api.command.args.GenericArguments$EnumValueElement.getValue(GenericArguments.java:857) ~[GenericArguments$EnumValueElement.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.api.command.args.PatternMatchingCommandElement.parseValue(PatternMatchingCommandElement.java:59) ~[PatternMatchingCommandElement.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.api.command.args.CommandElement.parse(CommandElement.java:83) ~[CommandElement.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.api.command.args.GenericArguments$SequenceCommandElement.parse(GenericArguments.java:273) ~[GenericArguments$SequenceCommandElement.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.api.command.spec.CommandSpec.populateContext(CommandSpec.java:284) ~[CommandSpec.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:330) ~[CommandSpec.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279) [SpongeCommandManager.class:1.8.9-1890-4.2.0-BETA-1762]
    at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [bd.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:815) [lm.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:794) [lm.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
    at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1762]
    at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

`GenericArguments.enumValue(effectTypeKey, EffectType.class),`

```
public enum EffectType {
    Fiesta(PokeEffects.Fiesta::new),
    Dark(PokeEffects.Dark::new);
```

**Comment by kashike** [comment]
A possible solution could look something like:

``` java
        @Override
        protected Object getValue(String choice) throws IllegalArgumentException {
            for (Field field : this.type.getFields()) {
                if (field.isEnumConstant()) {
                    T constant = (T) Enum.valueOf(this.type, field.getName());
                    if (constant.name().equalsIgnoreCase(choice)) {
                        return constant;
                    }
                }
            }
        }
```

**Comment by ryantheleach** [comment]
In addition, not sure if it's a bug with firstparsing, literal, or enum value.

```
                    GenericArguments.firstParsing(
                        GenericArguments.literal(Text.of("random", "random")),
                        GenericArguments.enumValue(effectTypeKey, EffectType.class)
                    ),
```

Doesn't tab complete or parse "random" at all.

**Comment by zml2008** [comment]
Text.of("random", "random") should be Text.of("random"), "random"

**Comment by ryantheleach** [comment]
Yeah sorry, silly mistake. the first one still stands though.

**Comment by hqppyz** [comment]
I found the same bug, did someone fixed that? Cause it's still a problem for me, i cant call any EnumPokemon :/

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/27f9b2891ad342d672c24b802abf13b78712e766
