### ISSUE TITLE
GenericArguments.playerOrSource crashes when passed a string that is invalid regex

### ISSUE THREAD

**Issue by nlipiarski** [SpongePowered/SpongeAPI#2062]
I'm using the newest stable sponge api release v7.2.0-20191102.164628-31 and I have a command that is created like this:
```
CommandSpec.builder()
                        .arguments(GenericArguments.playerOrSource(Text.of("player")),
                                GenericArguments.optional(GenericArguments.string(Text.of("material"))))
                        .alias("command")
```

When I run the command `/command dirt[]` the server throws an exception with the following stack trace:
```
['Player'/32, l='world', x=343.17, y=66.49, z=-70.38]: Unclosed character class near index 6
^dirt(
      ^
java.util.regex.PatternSyntaxException: Unclosed character class near index 6
^dirt[]
      ^
        at java.util.regex.Pattern.error(Unknown Source) ~[?:1.8.0_221]
        at java.util.regex.Pattern.clazz(Unknown Source) ~[?:1.8.0_221]
        at java.util.regex.Pattern.sequence(Unknown Source) ~[?:1.8.0_221]
        at java.util.regex.Pattern.expr(Unknown Source) ~[?:1.8.0_221]
        at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_221]
        at java.util.regex.Pattern.<init>(Unknown Source) ~[?:1.8.0_221]
        at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_221]
        at org.spongepowered.api.command.args.PatternMatchingCommandElement.getFormattedPattern(PatternMatchingCommandElement.java:89) ~[PatternMatchingCommandElement.class:1.12.2-7.1.6]
        at org.spongepowered.api.command.args.PatternMatchingCommandElement.parseValue(PatternMatchingCommandElement.java:65) ~[PatternMatchingCommandElement.class:1.12.2-7.1.6]
        at org.spongepowered.api.command.args.SelectorCommandElement.parseValue(SelectorCommandElement.java:57) ~[SelectorCommandElement.class:1.12.2-7.1.6]
        at org.spongepowered.api.command.args.GenericArguments$PlayerCommandElement.parseValue(GenericArguments.java:1425) ~[GenericArguments$PlayerCommandElement.class:1.12.2-7.1.6]
        at org.spongepowered.api.command.args.CommandElement.parse(CommandElement.java:83) ~[CommandElement.class:1.12.2-7.1.6]
        at org.spongepowered.api.command.args.GenericArguments$SequenceCommandElement.parse(GenericArguments.java:437) ~[GenericArguments$SequenceCommandElement.class:1.12.2-7.1.6]
        at org.spongepowered.api.command.spec.CommandSpec.populateContext(CommandSpec.java:340) ~[CommandSpec.class:1.12.2-7.1.6]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:387) ~[CommandSpec.class:1.12.2-7.1.6]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-7.1.6]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337) ~[SpongeCommandManager.class:1.12.2-7.1.6]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1156) ~[dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:855) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:842) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-7.1.6]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) ~[hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_221]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) ~[SpongeImplHooks.class:1.12.2-7.1.6]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(SourceFile:4130) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1581) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```
For some reason, it seems the parser is treating the name as a regular expression when checking if the user exists.

**Comment by dualspiral** [comment]
You should read the javadocs - https://jd.spongepowered.org/7.1.0/org/spongepowered/api/command/args/GenericArguments.html#playerOrSource-org.spongepowered.api.text.Text-

> This argument accepts the following inputs: ... **A regex that matches the beginning of one or more player's names**

So yes, this is intended. I need to check why the exception isn't being caught and quietened, but it's working as intended.

**Comment by electron93** [comment]
@dualspiral the problem seems to be on line 87:

https://github.com/SpongePowered/SpongeAPI/blob/0b58730f277417bbde5f1d5261dc51c87304a024/src/main/java/org/spongepowered/api/command/args/PatternMatchingCommandElement.java#L85-L91

I think it needs to be changed to something like this:

```java
    Pattern getFormattedPattern(String input) {
        input = "^" + Pattern.quote(input); // Anchor matches to the beginning -- this lets us use find()

        return Pattern.compile(input, Pattern.CASE_INSENSITIVE);

    }
```

The arguments themselves should not affect the behavior of the pattern.

**Comment by dualspiral** [comment]
Then it effectively ceases to become a regex, so no.

**Comment by nlipiarski** [comment]
As a follow up question, why are we treating the player name as a regular expression when the regular minecraft commands don't support this?  Is this intended or just a side effect of the given implementation?
