### ISSUE TITLE
IndexOutOfBoundsException when attempting to parse invalid block type

### ISSUE THREAD

**Issue by nlipiarski** [SpongePowered/SpongeAPI#2063]
Hello, at the moment I'm doing something like this:
```
Sponge.getRegistry().getType(BlockState.class, "dirt[]");
```

Where the second argument would usually be provided through a command argument.  When executing this code, the BlockState parser becomes unhappy and prints the following error:
```
java.lang.ArrayIndexOutOfBoundsException: 1
        at org.spongepowered.common.registry.type.BlockStateRegistryModule.getById(BlockStateRegistryModule.java:74) ~[BlockStateRegistryModule.class:1.12.2-7.1.6]
        at org.spongepowered.common.registry.SpongeGameRegistry.getType(SpongeGameRegistry.java:323) ~[SpongeGameRegistry.class:1.12.2-7.1.6]
```
From the javadoc for the getType method, it seems that if there is a problem parsing the value it should just return `Optional.empty()` instead of throwing an error.

This is happening to me on v7.1.0 and I also tried v7.2.0-20191102.164628-31 and it was having the same issue.

**Comment by nlipiarski** [comment]
Update: I realize this is a Sponge Common issue so I will move this issue there.
