### ISSUE TITLE
Can't get Biome Volume Factory with factory provider

### ISSUE THREAD

**Issue by realkarmakun** [SpongePowered/SpongeAPI#2410]
Running this code:
```java
Sponge.game().factoryProvider().provide(BiomeVolumeFactory.class);
```
Results in following exception:
```
[19:24:44] [Sponge-AsyncScheduler-0/ERROR] [sponge]: The Scheduler tried to run the task 'GenerateProceduralTerrain-A-#0' owned by 'spongetest' but an error occurred.
org.spongepowered.api.registry.TypeNotFoundException: Type 'interface org.spongepowered.api.world.volume.biome.BiomeVolumeFactory' has no factory registered!
	at org.spongepowered.common.registry.SpongeFactoryProvider.provide(SpongeFactoryProvider.java:189) ~[SpongeFactoryProvider.class:1.16.5-8.0.0-RC1060]
	at ru.meproject.rustmesponge.procedural.BiomeConstructionTask.run(BiomeConstructionTask.java:58) ~[BiomeConstructionTask.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:85) ~[Task$Builder.class:1.16.5-8.0.0-RC1060]
	at org.spongepowered.common.scheduler.SpongeScheduler.lambda$startTask$1(SpongeScheduler.java:278) ~[SpongeScheduler.class:1.16.5-8.0.0-RC1060]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

Using API version `8.0.0`

**Comment by dualspiral** [comment]
This isn't an API issue, but an implementation one. Please re-create this on https://github.com/SpongePowered/Sponge/issues/new/choose with all the required information (including version of server that you're running).

Thanks.
