### ISSUE TITLE
New Event Factory Changes Issues

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#673]
```
com.google.common.util.concurrent.ExecutionError: java.lang.ClassFormatError: Duplicate method name&signature in class file org/spongepowered/api/event/impl/PlayerJoinEvent$Impl
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199) ~[guava-17.0.jar:?]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[guava-17.0.jar:?]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[guava-17.0.jar:?]
    at org.spongepowered.api.event.SpongeEventFactory.createEvent(SpongeEventFactory.java:231) ~[SpongeEventFactory.class:?]
    at org.spongepowered.api.event.SpongeEventFactory.createPlayerJoin(SpongeEventFactory.java:1307) ~[SpongeEventFactory.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayerInject(ServerConfigurationManager.java:64) ~[ServerConfigurationManager.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:193) ~[ServerConfigurationManager.class:?]
    at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:120) ~[NetHandlerLoginServer.class:?]
    at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:66) ~[NetHandlerLoginServer.class:?]
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:265) ~[NetworkManager.class:?]
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:208) ~[NetworkSystem.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:796) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:380) ~[DedicatedServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:676) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:559) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file org/spongepowered/api/event/impl/PlayerJoinEvent$Impl
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_40]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_40]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_40]
    at org.spongepowered.api.util.event.factory.ClassGeneratorProvider$LocalClassLoader.defineClass(ClassGeneratorProvider.java:98) ~[ClassGeneratorProvider$LocalClassLoader.class:?]
    at org.spongepowered.api.util.event.factory.ClassGeneratorProvider.create(ClassGeneratorProvider.java:76) ~[ClassGeneratorProvider.class:?]
    at org.spongepowered.api.event.SpongeEventFactory$1.load(SpongeEventFactory.java:195) ~[SpongeEventFactory$1.class:?]
    at org.spongepowered.api.event.SpongeEventFactory$1.load(SpongeEventFactory.java:192) ~[SpongeEventFactory$1.class:?]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) ~[guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) ~[guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[guava-17.0.jar:?]
    ... 17 more
```
@Aaron1011 !

**Comment by Zidane** [comment]
```
[08:53:13] [main/ERROR] [ERR]: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 52: Insufficient maximum stack size.
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:297)
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(CheckMethodAdapter.java:450)
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:877)
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.util.CheckMethodAdapter.visitEnd(CheckMethodAdapter.java:1028)
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:837)
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:726)
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:412)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.asm.mixin.transformer.MixinTransformerModuleCheckClass.postApply(MixinTransformerModuleCheckClass.java:56)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.asm.mixin.transformer.MixinTransformer.postApply(MixinTransformer.java:564)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:525)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:360)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:101)
[08:53:13] [main/ERROR] [ERR]:     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[08:53:13] [main/ERROR] [ERR]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[08:53:13] [main/ERROR] [ERR]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[08:53:13] [main/ERROR] [ERR]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.vanilla.plugin.MinecraftPluginContainer.getInstance(MinecraftPluginContainer.java:55)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.vanilla.plugin.VanillaPluginManager.registerPlugin(VanillaPluginManager.java:66)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.vanilla.plugin.VanillaPluginManager.<init>(VanillaPluginManager.java:61)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.vanilla.plugin.VanillaPluginManager$$FastClassByGuice$$927f3919.newInstance(<generated>)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
[08:53:13] [main/ERROR] [ERR]:     at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.vanilla.SpongeVanilla.<init>(SpongeVanilla.java:80)
[08:53:13] [main/ERROR] [ERR]:     at org.spongepowered.vanilla.SpongeVanilla.<clinit>(SpongeVanilla.java:73)
[08:53:13] [main/ERROR] [ERR]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:53:13] [main/ERROR] [ERR]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:53:13] [main/ERROR] [ERR]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:53:13] [main/ERROR] [ERR]:     at java.lang.reflect.Method.invoke(Method.java:497)
[08:53:13] [main/ERROR] [ERR]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[08:53:13] [main/ERROR] [ERR]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:53:13] [main/ERROR] [ERR]:     at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[08:53:13] [main/ERROR] [ERR]:     at GradleStartServer.main(Unknown Source)
[08:53:13] [main/ERROR] [ERR]: Caused by: java.lang.IndexOutOfBoundsException: Insufficient maximum stack size.
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.tree.analysis.Frame.push(Frame.java:236)
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:276)
[08:53:13] [main/ERROR] [ERR]:     at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:199)
[08:53:13] [main/ERROR] [ERR]:     ... 75 more
[08:53:13] [main/INFO] [mixin]: Mixing world.difficulty.MixinEnumDifficulty into net.minecraft.world.EnumDifficulty
[08:53:13] [main/ERROR] [ERR]: Exception in thread "main" 
[08:53:13] [main/ERROR] [ERR]: java.lang.ExceptionInInitializerError
[08:53:13] [main/ERROR] [ERR]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:53:13] [main/ERROR] [ERR]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:53:13] [main/ERROR] [ERR]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:53:13] [main/ERROR] [ERR]:     at java.lang.reflect.Method.invoke(Method.java:497)
[08:53:13] [main/ERROR] [ERR]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[08:53:13] [main/ERROR] [ERR]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:53:13] [main/ERROR] [ERR]:     at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[08:53:13] [main/ERROR] [ERR]:     at GradleStartServer.main(Unknown Source)
[08:53:13] [main/ERROR] [ERR]: Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:
```

@Mumfrey I want to bring you in on this because this is blocking all development currently.

**Comment by Mumfrey** [comment]
How do you reproduce the error?

**Comment by Zidane** [comment]
@Mumfrey 

Set your API commit to https://github.com/SpongePowered/SpongeAPI/commit/fd11776c7593f8670e41292d943c53bb796ada50

...and run SpongeVanilla. Log in and boom server crash.

**Comment by Mumfrey** [comment]
SpongeVanilla? Why is this in SpongeAPI then?

**Comment by Mumfrey** [comment]
I can't reproduce this.

**Comment by progwml6** [comment]
@zidane can you make a branch of the vanilla implementation with the bug

**Comment by Mumfrey** [comment]
We already established, the issue only happens in IntelliJ apparently.

**Comment by Zidane** [comment]
I had to completely re-do my entire development workspace and install the latest IntelliJ (I was two builds behind) and it now works.

Sorry!
