### ISSUE TITLE
Error with player display name in PlayerJoinEvent

### ISSUE THREAD

**Issue by greatman** [SpongePowered/SpongeAPI#698]
In my PlayerJoinEvent, trying to use event.getUser().getDisplayNameData().getDisplayName().toString() throws a IllegalStateException
```
[20:47:45] [Server thread/ERROR] [Sponge]: Could not pass PlayerLoggedInEvent to
 SpongePlugin:GreatmancodeToolsLoader{1.0}
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
        at com.google.common.base.Absent.get(Absent.java:47) ~[minecraft_server.1.8.jar:?]
        at net.minecraft.entity.player.EntityPlayerMP.getDisplayNameData(EntityPlayerMP.java:268) ~[qw.class:?]
        at com.greatmancode.craftconomy3.tools.events.sponge.PlayerJoinEventListener.onPlayerJoinEvent(PlayerJoinEventListener.java:30) ~[PlayerJoinEventListener.class:?]
```

@gabizou said yesterday he was looking at fixing it. This is why it is not working: https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/SpongeDisplayNameDataProcessor.java#L150

**Comment by simon816** [comment]
Until this is fixed, you can do
`getUser().getOrCreate(DisplayNameData.class).get()`

**Comment by nikosgram13** [comment]
Can you re-open this issue in SpongeCommon as it's most relevant there.

https://github.com/SpongePowered/SpongeCommon/issues

**Comment by gabizou** [comment]
This should be resolved by now. @greatman can you test to verify?

**Comment by Zidane** [comment]
New event framework changes this event and this was a data-related problem resolved.
