### ISSUE TITLE
World Copy From Existing Source

### ISSUE THREAD

**Issue by FerusGrim** [SpongePowered/SpongeAPI#750]
Currently, copying worlds requires manually modifying NBT files to change the World UUID/Name (speculation), otherwise you'll run into quite a bit of `ReportedException` and `ConcurrentModificationError`s (eg; it appears the server can't tell the difference, and attempts to make changes to both maps as if they were a single instance).

(NOTE, the below log is _definitely_ truncated)

```java
[12:40:42] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:770) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:385) ~[DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_45]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_45]
	at net.minecraft.world.gen.ChunkProviderServer.unloadAllChunks(ChunkProviderServer.java:98) ~[ChunkProviderServer.class:?]
	at net.minecraft.server.management.PlayerManager.updatePlayerInstances(PlayerManager.java:94) ~[PlayerManager.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:230) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:764) ~[MinecraftServer.class:?]
	... 4 more
[12:40:42] [Server thread/ERROR]: This crash report has been saved to: E:\Programming\Projects\Sponge\run\server\.\crash-reports\crash-2015-07-05_12.40.42-server.txt
[12:40:42] [pool-2-thread-1/INFO]: World was prepared and loaded successfully. If you're a player, we'll teleport you, now.
[12:41:42] [Server Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
[12:41:42] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
```

It would be nice if there was an existing method in the API which could pass this responsibility to the implementation.

**Comment by Zidane** [comment]
API to do this is now in master. @bloodmc will implement it when time allows.
