### ISSUE TITLE
On client, user address is not InetSocketAddress

### ISSUE THREAD

**Issue by jb-aero** [SpongePowered/SpongeAPI#754]
```
java.lang.ClassCastException: io.netty.channel.local.LocalAddress cannot be cast to java.net.InetSocketAddress
	at net.minecraft.network.NetworkManager.getAddress(NetworkManager.java:50)
	at net.minecraft.network.NetHandlerPlayServer.getAddress(NetHandlerPlayServer.java:92)
	at com.laytonsmith.abstraction.sponge.entities.SpongeMCPlayer.getAddress(SpongeMCPlayer.java:92)
	at com.laytonsmith.core.functions.PlayerManagement$pinfo.exec(PlayerManagement.java:907)
	at com.laytonsmith.core.Script.eval(Script.java:352)
	at com.laytonsmith.core.Script.seval(Script.java:239)
	at com.laytonsmith.core.functions.DataHandling$eval.execs(DataHandling.java:3746)
```
Occurred when calling
```
player.getConnection().getAddress();
```
with the Forge version of Sponge running on the client.

**Comment by simon816** [comment]
SpongeAPI is not the correct repo to report this crash. This is an issue with the Sponge mod not the API.
