### ISSUE TITLE
Tab complete NPE

### ISSUE THREAD

**Issue by aleshkanet** [SpongePowered/SpongeAPI#796]
When I try to autocomplete command and press "Tab", i got error:
```
[12:31:59] [Server thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_51]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.management.UserListOps.func_152699_b(SourceFile:39) ~[sp.class:?]
        at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9) ~[sp.class:?]
        at net.minecraft.server.management.UserList.func_152683_b(SourceFile:56) ~[ss.class:?]
        at org.spongepowered.common.service.permission.UserSubject.getOpLevel(UserSubject.java:93) ~[UserSubject.class:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at org.spongepowered.common.service.permission.UserSubject$1.getParent(UserSubject.java:55) ~[UserSubject$1.class:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at org.spongepowered.common.service.permission.base.SingleParentMemorySubjectData.getParents(SingleParentMemorySubjectData.java:51) ~[SingleParentMemorySubjectData.class:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at org.spongepowered.common.service.permission.base.SpongeSubject.getDataPermissionValue(SpongeSubject.java:65) ~[SpongeSubject.class:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at org.spongepowered.common.service.permission.base.SpongeSubject.getPermissionValue(SpongeSubject.java:58) ~[SpongeSubject.class:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at org.spongepowered.common.service.permission.UserSubject.getPermissionValue(UserSubject.java:115) ~[UserSubject.class:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at net.minecraft.entity.player.EntityPlayerMP.getPermissionValue(EntityPlayerMP.java:147) ~[qw.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:129) ~[qw.class:?]
 
        at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:141) ~[qw.class:?]
 
        at net.minecraft.entity.player.EntityPlayerMP.func_70003_b(EntityPlayerMP.java:49) ~[qw.class:?]
        at net.minecraft.command.CommandBase.func_71519_b(SourceFile:40) ~[z.class:?]
        at org.spongepowered.common.command.MinecraftCommandWrapper.testPermission(MinecraftCommandWrapper.java:157) ~[sponge-1.8-1499-2.1DEV-544.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at org.spongepowered.api.util.command.dispatcher.SimpleDispatcher$2.apply(SimpleDispatcher.java:409) ~[sponge-1.8-1499-2.1DEV-544.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at org.spongepowered.api.util.command.dispatcher.SimpleDispatcher$2.apply(SimpleDispatcher.java:405) ~[sponge-1.8-1499-2.1DEV-544.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at com.google.common.base.Predicates$CompositionPredicate.apply(Predicates.java:552) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:645) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:268) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226) ~[minecraft_server.1.8.jar:?]
        at org.spongepowered.api.util.command.dispatcher.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:356) ~[SimpleDispatcher.class:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at org.spongepowered.api.service.command.SimpleCommandService.getSuggestions(SimpleCommandService.java:298) ~[SimpleCommandService.class:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
        at net.minecraft.command.ServerCommandManager.func_180524_a(SourceFile:164) ~[cl.class:?]
        at net.minecraft.server.MinecraftServer.func_180506_a(MinecraftServer.java:837) ~[MinecraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1146) ~[rj.class:?]
        at net.minecraft.network.play.client.C14PacketTabComplete.func_180756_a(SourceFile:46) ~[lt.class:?]
        at net.minecraft.network.play.client.C14PacketTabComplete.func_148833_a(SourceFile:10) ~[lt.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_51]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
        ... 5 more
```

**Comment by Aaron1011** [comment]
Pinging @zml2008, as this appears to be related to permissions, judging from the stacktrace.

**Comment by simon816** [comment]
This is the same as SpongePowered/SpongeCommon#117
It's because for some reason the game profile resolver I wrote is not caching correctly, and the profile returns null
```
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
```
I'll try and fix it soon.

**Comment by zml2008** [comment]
Closing as dupe
